---
- name: Deploy Jenkins Controller on Proxmox VM
  hosts: jenkins_controller
  become: yes
  become_method: sudo  # Explicitly set sudo
  become_user: root  # Run as root
  roles:
    - common
    - jenkins
    - firewall
    - postinstall
